Run create scripts in CI to test them.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -8,6 +8,7 @@ env:
   SECRET: testing
   TESTING: 1
   DATABASE_URL: sqlite://./tests.sqlite
+  PORT: 8000
 
 jobs:
   test:
@@ -55,15 +56,20 @@ jobs:
     - name: Install Node deps
       run: npm i
 
+    # Main test suite
+
     - name: Run the tests
       run: npm run test
 
     - name: Run the e2e tests
       run: npm run test-e2e
 
+   # Test suite with PostgreSQL as a db
+
     - name: Set up PostgreSQL
       run: |
-        sudo apt install postgresql libpq-dev
+        sudo apt update
+        sudo apt install -y postgresql libpq-dev
         sudo service postgresql start
         sudo -u postgres createuser --superuser "$USER"
       if: runner.os == 'Linux'
@@ -71,3 +77,45 @@ jobs:
     - name: Run the tests on Postgres
       run: npm run test-postgres
       if: runner.os == 'Linux'
+
+    # npm init "create" script tests
+
+    - name: Link local packages for create tests
+      run: npm link
+
+    - name: Create temporary directory for create tests
+      run: mkdir test-create-scripts
+
+    - name: Test npm create sitefox-fullstack
+      working-directory: ./test-create-scripts
+      run: |
+        set -e
+        # Use absolute path for npm create as we are in a different working dir
+        npm create sitefox-fullstack test-fullstack-app --prefix ../
+        cd test-fullstack-app
+        npm install
+        make watch &
+        if timeout 30 bash -c 'until echo > /dev/tcp/localhost/$PORT; do echo -n "."; sleep 1; done 2>/dev/null'; then
+          echo "Server started successfully."
+        else
+          echo "Server failed to start within 30 seconds."
+          exit 1 # Exit with error if server fails to start
+        fi
+        killall node java || true # Allow failure if processes not found
+
+    - name: Test npm create sitefox-nbb
+      working-directory: ./test-create-scripts
+      run: |
+        set -e
+        # Use absolute path for npm create as we are in a different working dir
+        npm create sitefox-nbb test-nbb-app --prefix ../
+        cd test-nbb-app
+        npm install
+        npm run serve &
+        if timeout 30 bash -c 'until echo > /dev/tcp/localhost/$PORT; do echo -n "."; sleep 1; done 2>/dev/null'; then
+          echo "Server started successfully."
+        else
+          echo "Server failed to start within 30 seconds."
+          exit 1 # Exit with error if server fails to start
+        fi
+        killall node || true # Allow failure if process not found
